In [162]:
from sklearn import clone #used to clone the current weights of the algorithm wrong, because it creates a shallow copy

from sklearn.linear_model import SGDRegressor
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from copy import deepcopy

In [303]:
m = 10000
X = 2* np.random.rand(m,1)
y = 4+3*X*+5*X**2+np.random.randn(m,1)


In [333]:
X_train,X_val, y_train,y_val = train_test_split(X,y,test_size = 0.2)
poly_scaler = Pipeline([
                ("poly_features", PolynomialFeatures(degree = 90, include_bias = False))
                ,("std_scaler",StandardScaler())
            ])
X_train_poly_scaled = poly_scaler.fit_transform(X_train)
X_val_poly_scaled = poly_scaler.transform(X_val)
sgd_reg = SGDRegressor(max_iter = 1, tol = -np.infty, warm_start = True, penalty = None, learning_rate= "constant", eta0 = 0.0005)

In [322]:
#convert 2d array to 1D to fit sgd arguments

y_val = y_val.flatten()
#alternatively y_train.ravel()
#or y_val.ravel()

In [323]:
minimum_val_error = float("inf")
best_epoch = None
best_model = None
for epoch in range(1000):
    sgd_reg.fit(X_train_poly_scaled, y_train.ravel())
    y_val_predict = sgd_reg.predict(X_val_poly_scaled)
    val_error = mean_squared_error(y_val, y_val_predict)
    if(val_error < minimum_val_error):
        minimum_val_error = val_error
        best_epoch = epoch
        best_model = deepcopy(sgd_reg)

In [324]:

best_epoch,X_val_poly_scaled[:1]

(360,
 array([[1.61586445e+00, 2.61101791e+00, 4.21905101e+00, 6.81741453e+00,
         1.10160178e+01, 1.78003914e+01, 2.87630197e+01, 4.64771409e+01,
         7.51007595e+01, 1.21352647e+02, 1.96089428e+02, 3.16853935e+02,
         5.11993009e+02, 8.27311300e+02, 1.33682292e+03, 2.16012462e+03,
         3.49046858e+03, 5.64012408e+03, 9.11367597e+03, 1.47264650e+04,
         2.37959712e+04, 3.84510638e+04, 6.21317070e+04, 1.00396416e+05,
         1.62227000e+05, 2.62136841e+05, 4.23577602e+05, 6.84443987e+05,
         1.10596871e+06, 1.78709551e+06, 2.88770410e+06, 4.66613838e+06,
         7.53984712e+06, 1.21833709e+07, 1.96866759e+07, 3.18109996e+07,
         5.14022633e+07, 8.30590897e+07, 1.34212230e+08, 2.16868771e+08,
         3.50430537e+08, 5.66248245e+08, 9.14980407e+08, 1.47848431e+09,
         2.38903023e+09, 3.86034901e+09, 6.23780072e+09, 1.00794404e+10,
         1.62870094e+10, 2.63175994e+10, 4.25256733e+10, 6.87157235e+10,
         1.11035295e+11, 1.79417985e+11, 2.89

In [325]:
best_model.intercept_, best_model.coef_




(array([2.14721319e+13]),
 array([-1.25549537e+14, -1.87619826e+14, -2.44493684e+14, -3.24129908e+14,
        -4.48799718e+14, -6.49000003e+14, -9.73982928e+14, -1.50658672e+15,
        -2.38803199e+15, -3.86092492e+15, -6.34460730e+15, -1.05678547e+16,
        -1.78034508e+16, -3.02842018e+16, -5.19428992e+16, -8.97319934e+16,
        -1.55982850e+17, -2.72632833e+17, -4.78814173e+17, -8.44503051e+17,
        -1.49510895e+18, -2.65583953e+18, -4.73185324e+18, -8.45324383e+18,
        -1.51375817e+19, -2.71657877e+19, -4.88454217e+19, -8.79779457e+19,
        -1.58705839e+20, -2.86687491e+20, -5.18507179e+20, -9.38791984e+20,
        -1.70135555e+21, -3.08587228e+21, -5.60101752e+21, -1.01721651e+22,
        -1.84829239e+22, -3.35964666e+22, -6.10855085e+22, -1.11086492e+23,
        -2.02031956e+23, -3.67427854e+23, -6.68150900e+23, -1.21474278e+24,
        -2.20778825e+24, -4.01096390e+24, -7.28302506e+24, -1.32159450e+25,
        -2.39638966e+25, -4.34146408e+25, -7.85738713e+25, -1.

In [337]:
best_model.predict(poly_scaler.fit_transform([[1.5]]))

array([2.14721319e+13])

In [336]:
poly_features = PolynomialFeatures(degree = 90, include_bias = False)
best_model.predict(poly_features.fit_transform([[1.5]]))

array([1.68834133e+50])