In [39]:
#Testing some MSE python functions

In [40]:
import numpy as np

In [41]:
X = 2* np.random.rand(100,1)


In [42]:
y = 4+3*X+np.random.randn(100,1)


In [43]:
X_b = np.c_[np.ones((100,1)),X] # we have to add the row of np.ones in order to make there be a x0 value in theta best

In [64]:
theta_best = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y) #normal equation (XTX)^-1*XT*y
#complexity of O(n^2.4 - n^3)

In [65]:
theta_best

array([[3.6612508 ],
       [3.16026959]])

In [66]:
#theta_best = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)

In [67]:
#theta_best

In [68]:
X_new = np.array([[0],[2]])

In [69]:
X_new_b = np.c_[np.ones((2,1)),X_new]

In [70]:
X_new_b

array([[1., 0.],
       [1., 2.]])

In [71]:
y_predict = X_new_b.dot(theta_best)

In [72]:
y_predict

array([[3.6612508 ],
       [9.98178998]])

In [74]:
import matplotlib.pyplot as plt

In [1]:
"""""""""
plt.plot(X_new,y_predict, "r-")
plt.plot(X,y,"b.")
plt.axis([0,2,0,15])
plt.show()
"""""""""

'\nplt.plot(X_new,y_predict, "r-")\nplt.plot(X,y,"b.")\nplt.axis([0,2,0,15])\nplt.show()\n'

In [77]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X,y)
lin_reg.intercept_, lin_reg.coef_

(array([3.6612508]), array([[3.16026959]]))

In [78]:
lin_reg.predict(X_new)

array([[3.6612508 ],
       [9.98178998]])