In [9]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

In [10]:
m = 100
X = 6*np.random.rand(m,1)-3
y = 0.5*X**2+X+2+np.random.randn(m,1)

In [13]:
poly_features = PolynomialFeatures(degree = 2, include_bias = False)
X_poly = poly_features.fit_transform(X)#transform it into it, and the powers of the function


In [14]:
lin_reg = LinearRegression()
lin_reg.fit(X_poly,y)
lin_reg.intercept_,lin_reg.coef_

(array([1.92995576]), array([[1.04135197, 0.52731208]]))

In [18]:
lin_reg.predict([[3,9]])

array([[9.79982037]])

In [19]:
lin_reg.predict(poly_features.fit_transform([[3]]))

array([[9.79982037]])

NameError: name 'log_reg' is not defined